<?php
/**
 * @file
 * Update and install functions for FileField Sources.
 */

/**
 * Implementation of hook_install().
 */
function footnotes_fixer_install() {
  db_query("UPDATE {system} SET weight = 20 WHERE type = 'module' AND name = 'footnotes_fixer'");
}

/**
 * Set the module weight.
 */
function footnotes_fixer_update_7100() {
  db_query("UPDATE {system} SET weight = 20 WHERE type = 'module' AND name = 'footnotes_fixer'");
}
